### ISSUE TITLE
[TODO] theming

### ISSUE THREAD

**Issue by cjdoris** [cjdoris/Bokeh.jl#15]
- [ ] Add types `Theme` and `SerializedDocument`.
- [ ] Change most functions which take a `Document` to take a `SerializedDocument` instead, in particular the `backend_display` functions.
- [ ] Add themes to `Document` and `Serializer` and apply the theme during serialization.
- [ ] Add `backend_theme` to allow the backend to specify a theme, so the Blink backend can set `sizing_mode="stretch_both"`.
- [ ] Add functions for reading/writing themes to/from disk.
- [ ] Add functions for modifying themes more easily.
- [ ] Either reintroduce the `Figure` type, or consider `Figure` and `Plot` to be the same when theming as a special case.
- [ ] Traverse the full MRO when applying themes.
